from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('verify-email/', views.verify_email, name='verify_email'),
    path('resend-verification/', views.resend_verification, name='resend_verification'),
    path('login/', views.login, name='login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-reset-code/', views.verify_reset_code, name='verify_reset_code'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('profile/', views.get_profile, name='get_profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('profile/upload-picture/', views.upload_profile_picture, name='upload_profile_picture'),    
    path('profile/stats/', views.get_user_stats, name='get_user_stats'),
    path('profile/activity/', views.get_activity_timeline, name='get_activity_timeline'),    
    path('study-goals/', views.get_study_goals, name='get_study_goals'),
    path('study-goals/create/', views.create_study_goal, name='create_study_goal'),
    path('study-goals/<uuid:goal_id>/update/', views.update_study_goal, name='update_study_goal'),
    path('study-goals/<uuid:goal_id>/delete/', views.delete_study_goal, name='delete_study_goal'),
    path('study-goals/<uuid:goal_id>/toggle/', views.toggle_study_goal, name='toggle_study_goal'),
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/dashboard/stats/', views.admin_dashboard_stats, name='admin_dashboard_stats'),
    path('admin/verify/', views.admin_verify_access, name='admin_verify_access'),
    path('admin/users/', views.admin_get_users, name='admin_get_users'),
    path('admin/users/<uuid:user_id>/', views.admin_get_user_detail, name='admin_get_user_detail'),
    path('admin/users/<uuid:user_id>/update/', views.admin_update_user, name='admin_update_user'),
    path('admin/users/<uuid:user_id>/suspend/', views.admin_suspend_user, name='admin_suspend_user'),
    path('admin/users/<uuid:user_id>/unsuspend/', views.admin_unsuspend_user, name='admin_unsuspend_user'),
    path('admin/users/<uuid:user_id>/delete/', views.admin_delete_user, name='admin_delete_user'),
    path('admin/guilds/', views.admin_get_guilds, name='admin_get_guilds'),
    path('admin/guilds/<uuid:guild_id>/', views.admin_get_guild_detail, name='admin_get_guild_detail'),
    path('admin/analytics/', views.admin_get_analytics, name='admin_get_analytics'),
    path('admin/notifications/', views.admin_get_notifications, name='admin_get_notifications'),
    path('admin/notifications/<uuid:notification_id>/read/', views.admin_mark_notification_read, name='admin_mark_notification_read'),
    path('admin/notifications/read-all/', views.admin_mark_all_notifications_read, name='admin_mark_all_notifications_read'),
    path('admin/notifications/<uuid:notification_id>/delete/', views.admin_delete_notification, name='admin_delete_notification'),
    path('discovery/users/', views.discovery_users, name='discovery_users'),
    path('discovery/user/<uuid:user_id>/', views.discovery_user_detail, name='discovery_user_detail'),
    path('connections/send/<uuid:user_id>/', views.send_connection_request, name='send_connection_request'),
    path('connections/requests/', views.get_connection_requests, name='get_connection_requests'),
    path('connections/accept/<uuid:request_id>/', views.accept_connection_request, name='accept_connection_request'),
    path('connections/reject/<uuid:request_id>/', views.reject_connection_request, name='reject_connection_request'),

]