# Generated by Django 5.2.8 on 2026-03-21 13:10

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='message_attachments/'),
        ),
    ]
